FROM fffaraz/qt:mxe

RUN \
    cd /opt/mxe && \
    NPROC=$(($(nproc)+4)) && \
    make --jobs=$NPROC JOBS=$NPROC MXE_TARGETS='i686-w64-mingw32.static' qt6-qtbase && \
    ln -s /opt/mxe/usr/bin/i686-w64-mingw32.static-qmake-qt6 /usr/bin/qmake && \
    qmake --version && \
    exit 0
