FROM fffaraz/qt:mxe

RUN \
    cd /opt/mxe && \
    make --jobs=$(nproc) JOBS=$(nproc) MXE_TARGETS='x86_64-w64-mingw32.static' qt6-qtbase && \
    exit 0

ENV PATH="${PATH}:/opt/mxe/usr/x86_64-w64-mingw32.static/qt6/bin"

RUN \
    echo $PATH &&\
    qmake --version && \
    exit 0
